export const WORD_POOL = [
    "apple", "table", "chair", "glass", "stone", "phone", "brick", "brush", "smile", "happy",
    "water", "cloud", "light", "night", "music", "sound", "earth", "flower", "green", "green",
    "dream", "jump", "fast", "slow", "star", "moon", "book", "desk", "pen", "pencil",
    "read", "write", "talk", "walk", "run", "fall", "stop", "time", "place", "learn",
    "sleep", "wake", "dance", "game", "card", "coin", "key", "lock", "gold", "ring",
    "blue", "red", "pink", "green", "yellow", "brown", "black", "white", "orange", "gray",
    "love", "kind", "good", "happy", "sad", "funny", "cool", "smart", "kind", "brave",
    "strong", "hard", "soft", "rich", "poor", "warm", "cold", "chill", "bright", "shiny",
    "calm", "wild", "crazy", "angry", "fun", "snow", "rain", "wind", "fire", "storm",
    "river", "lake", "sea", "ocean", "mount", "hill", "valley", "forest", "desert", "island",
    "plane", "train", "car", "bus", "bike", "ship", "boat", "truck", "scooter", "horse",
    "cat", "dog", "bird", "fish", "lion", "tiger", "bear", "wolf", "deer", "fox",
    "cow", "sheep", "goat", "chicken", "duck", "elephant", "giraffe", "zebra", "camel", "monkey",
    "apple", "peach", "melon", "grape", "lemon", "plum", "pear", "kiwi", "date", "fig",
    "carrot", "potato", "onion", "beans", "corn", "spinach", "lettuce", "tomato", "chili", "cabbage",
    "salt", "sugar", "pepper", "olive", "bacon", "bread", "cheese", "butter", "milk", "egg",
    "meat", "fish", "chicken", "beef", "pork", "bake", "boil", "fry", "grill", "steam",
    "sweet", "bitter", "sour", "salty", "spicy", "tasty", "fresh", "roast", "mash", "cook",
    "eat", "drink", "serve", "plate", "knife", "fork", "spoon", "cup", "mug", "glass",
    "salt", "pepper", "knife", "fork", "bowl", "plate", "spoon", "cup", "fork", "spoon",
    "sauce", "beet", "fruit", "meat", "lunch", "dinner", "break", "lemon", "fruit", "berry",
    "bake", "fry", "steam", "grill", "roast", "boil", "roast", "stew", "broil", "poach",
    "clean", "wash", "dry", "fold", "iron", "sweep", "mop", "dust", "vacuum", "scrub",
    "paint", "color", "draw", "sketch", "shade", "sculpt", "glue", "cut", "sew", "craft",
    "work", "study", "read", "write", "plan", "think", "talk", "learn", "teach", "listen",
    "speak", "argue", "debate", "discuss", "gather", "meet", "join", "share", "give", "help",
    "love", "care", "hug", "kiss", "hold", "talk", "call", "chat", "email", "text",
    "listen", "hear", "see", "watch", "feel", "smell", "touch", "move", "stand", "sit",
    "stand", "walk", "run", "jump", "play", "work", "rest", "stop", "start", "finish",
    "go", "stay", "return", "leave", "enter", "exit", "buy", "sell", "pay", "save",
    "spend", "share", "keep", "lend", "borrow", "find", "lose", "search", "look", "seek",
    "fix", "build", "create", "make", "build", "plant", "grow", "cut", "dig", "harvest",
    "clean", "wash", "cook", "bake", "grill", "serve", "taste", "smell", "look", "watch"
  ];

  export const TIME_OPTIONS = [5, 15, 30, 60, 120] as const;